// AUTO-GENERATED by `npm run icons`. Do not edit by hand.
// Lists the slugs that have a locally-hosted icon in /public/anime-icons.
// Empty until you run the script; until then the app uses a live favicon
// service (and a letter-tile fallback).
export const LOCAL_ICONS: ReadonlySet<string> = new Set([]);
