// ---------------------------------------------------------------------------
// Anime Index — a directory of anime sites across the whole landscape:
// official/legal services, free (unofficial) sites, region-blocked ones, and
// the graveyard of shut-down ones.
//
// This is an INFORMATIONAL catalog (in the spirit of everythingmoe.com / FMHY).
// It does NOT host, stream, proxy, or deep-link to any content — "Visit" links
// are only attached to official/legal services. Entries marked "free" are
// unofficial; statuses, regions, and dates are community-sourced, approximate,
// and change often (current as of mid-2026).
// ---------------------------------------------------------------------------

export type SiteStatus = "legal" | "free" | "shutdown";
export type SiteKind =
  | "stream"
  | "donghua"
  | "manga"
  | "novel"
  | "download"
  | "database"
  | "schedule"
  | "app"
  | "news";

export interface AnimeSite {
  slug: string;
  name: string;
  /** Only set for official/legal services — we don't deep-link unofficial ones. */
  url?: string;
  status: SiteStatus;
  kind: SiteKind;
  blurb: string;
  features: string[];
  founded?: number;
  /** Year it shut down / merged away, for status === "shutdown". */
  endedYear?: number;
  /** Primary availability, e.g. "Worldwide", "Japan", "Latin America". */
  region?: string;
  /** Countries where it's been ISP- or court-blocked. */
  blockedIn?: string[];
  /** What replaced it / what it merged into. */
  successor?: string;
  /** Optional hand-picked styling; otherwise derived deterministically. */
  emoji?: string;
  gradient?: string;
  featured?: boolean;
}

export const ANIME_SITES: AnimeSite[] = [
  // =========================================================================
  // LEGAL — global streaming
  // =========================================================================
  {
    slug: "crunchyroll",
    name: "Crunchyroll",
    url: "https://www.crunchyroll.com",
    status: "legal",
    kind: "stream",
    blurb:
      "The dominant global anime service (Sony-owned); absorbed Funimation, Wakanim, and VRV into one catalog of 1000+ titles.",
    features: ["Subbed", "Dubbed", "Simulcast", "Free w/ ads"],
    founded: 2006,
    region: "Worldwide (ex-China)",
    emoji: "🍥",
    gradient: "from-amber-400 to-orange-500",
    featured: true,
  },
  {
    slug: "hidive",
    name: "HIDIVE",
    url: "https://www.hidive.com",
    status: "legal",
    kind: "stream",
    blurb:
      "Sentai-backed streamer known for niche simulcasts and dubs that don't land on Crunchyroll.",
    features: ["Subbed", "Dubbed", "Simulcast", "Exclusives"],
    founded: 2017,
    region: "US / CA / UK / AU / NZ / IE",
    emoji: "🌊",
    gradient: "from-sky-500 to-indigo-500",
    featured: true,
  },
  {
    slug: "netflix",
    name: "Netflix",
    url: "https://www.netflix.com",
    status: "legal",
    kind: "stream",
    blurb:
      "Heavy investor in anime originals (Cyberpunk: Edgerunners, Devilman Crybaby) plus a rotating licensed catalog.",
    features: ["Subbed", "Dubbed", "Originals", "4K"],
    founded: 2007,
    region: "Worldwide",
    emoji: "🅽",
    gradient: "from-red-500 to-rose-600",
  },
  {
    slug: "prime-video",
    name: "Amazon Prime Video",
    url: "https://www.primevideo.com",
    status: "legal",
    kind: "stream",
    blurb:
      "Large licensed library plus add-on channels (Crunchyroll, Anime Generation, Animax). Once ran the separate 'Anime Strike'.",
    features: ["Subbed", "Dubbed", "Channels", "4K"],
    founded: 2006,
    region: "Worldwide",
    emoji: "📦",
    gradient: "from-cyan-400 to-blue-500",
  },
  {
    slug: "disney-plus",
    name: "Disney+",
    url: "https://www.disneyplus.com",
    status: "legal",
    kind: "stream",
    blurb:
      "Carries select high-profile anime simulcasts and exclusives (Bleach: TYBW, Tokyo Revengers) in many regions.",
    features: ["Subbed", "Dubbed", "Exclusives"],
    region: "Worldwide",
    emoji: "🏰",
    gradient: "from-indigo-500 to-violet-600",
  },
  {
    slug: "hulu",
    name: "Hulu",
    url: "https://www.hulu.com",
    status: "legal",
    kind: "stream",
    blurb: "US streamer with a sizeable licensed anime catalog, often mirroring Crunchyroll titles.",
    features: ["Subbed", "Dubbed"],
    region: "United States",
    emoji: "🟩",
    gradient: "from-lime-400 to-emerald-500",
  },
  {
    slug: "max",
    name: "Max (HBO Max)",
    url: "https://www.max.com",
    status: "legal",
    kind: "stream",
    blurb: "Carries Crunchyroll-licensed anime in the US plus regional deals in Latin America and Europe.",
    features: ["Subbed", "Dubbed"],
    region: "US / LATAM / EU",
    emoji: "🟣",
    gradient: "from-purple-500 to-indigo-500",
  },
  {
    slug: "tubi",
    name: "Tubi",
    url: "https://tubitv.com",
    status: "legal",
    kind: "stream",
    blurb: "Free, ad-supported and fully legal — one of the largest free anime libraries in North America.",
    features: ["Free w/ ads", "Subbed", "Dubbed", "No account"],
    region: "US / CA / AU / MX",
    emoji: "📺",
    gradient: "from-fuchsia-500 to-pink-500",
    featured: true,
  },
  {
    slug: "pluto-tv",
    name: "Pluto TV",
    url: "https://pluto.tv",
    status: "legal",
    kind: "stream",
    blurb: "Free ad-supported service with always-on anime channels in the US and several other regions.",
    features: ["Free w/ ads", "Live channels"],
    region: "US / EU / LATAM",
    emoji: "🪐",
    gradient: "from-sky-500 to-indigo-500",
  },
  {
    slug: "plex",
    name: "Plex",
    url: "https://watch.plex.tv",
    status: "legal",
    kind: "stream",
    blurb: "Free ad-supported on-demand and live anime alongside its media-server features.",
    features: ["Free w/ ads", "On-demand"],
    region: "Worldwide",
    emoji: "🟧",
    gradient: "from-amber-400 to-orange-500",
  },
  {
    slug: "crackle",
    name: "Crackle",
    url: "https://www.crackle.com",
    status: "legal",
    kind: "stream",
    blurb: "Free, ad-supported streamer (formerly Sony Crackle) with a rotating selection of anime.",
    features: ["Free w/ ads"],
    region: "North America",
    emoji: "🍿",
    gradient: "from-red-500 to-rose-600",
  },
  {
    slug: "retrocrush",
    name: "RetroCrush",
    url: "https://www.retrocrush.tv",
    status: "legal",
    kind: "stream",
    blurb: "Free, ad-supported service focused on classic and retro anime from the 70s–2000s.",
    features: ["Free w/ ads", "Subbed", "Dubbed", "Retro"],
    founded: 2020,
    region: "North America",
    emoji: "📼",
    gradient: "from-yellow-400 to-amber-500",
  },
  {
    slug: "midnight-pulp",
    name: "Midnight Pulp",
    url: "https://www.midnightpulp.com",
    status: "legal",
    kind: "stream",
    blurb: "Cult and genre streaming with a curated free anime section.",
    features: ["Free w/ ads", "Cult / genre"],
    region: "Worldwide",
  },
  {
    slug: "asiancrush",
    name: "AsianCrush",
    url: "https://www.asiancrush.com",
    status: "legal",
    kind: "stream",
    blurb: "Asian cinema and TV platform with a free, legal anime selection.",
    features: ["Free w/ ads", "Asian media"],
    region: "Worldwide",
  },
  {
    slug: "contv",
    name: "CONtv",
    url: "https://www.contv.com",
    status: "legal",
    kind: "stream",
    blurb: "Comic-con-branded streamer carrying genre TV and a slate of anime.",
    features: ["Free w/ ads", "Genre"],
    region: "Worldwide",
  },
  {
    slug: "toku",
    name: "Toku",
    url: "https://www.watchtoku.com",
    status: "legal",
    kind: "stream",
    blurb: "Action-and-anime channel from Olympusat, available on demand and as a linear channel.",
    features: ["Subbed", "Dubbed", "Tokusatsu"],
    region: "North America",
  },
  {
    slug: "gundam-info",
    name: "Gundam.info",
    url: "https://en.gundam.info",
    status: "legal",
    kind: "stream",
    blurb: "Bandai's official free hub streaming Gundam series and shorts worldwide.",
    features: ["Free", "Official", "Gundam"],
    region: "Worldwide",
  },

  // ----- Legal streaming: Japan -----
  {
    slug: "abema",
    name: "ABEMA",
    url: "https://abema.tv",
    status: "legal",
    kind: "stream",
    blurb: "Major Japanese free/premium streamer with a huge same-day anime lineup.",
    features: ["Subbed (JP)", "Simulcast", "Free + premium"],
    founded: 2016,
    region: "Japan",
    emoji: "🇯🇵",
    gradient: "from-emerald-400 to-teal-500",
  },
  {
    slug: "danime-store",
    name: "dAnime Store",
    url: "https://animestore.docomo.ne.jp",
    status: "legal",
    kind: "stream",
    blurb: "NTT Docomo's anime-only subscription — one of the largest catalogs in Japan.",
    features: ["JP audio", "Huge catalog"],
    region: "Japan",
  },
  {
    slug: "u-next",
    name: "U-NEXT",
    url: "https://video.unext.jp",
    status: "legal",
    kind: "stream",
    blurb: "Premium Japanese VOD service with a deep anime and film library; absorbed Paravi.",
    features: ["JP audio", "Premium", "Films"],
    region: "Japan",
  },
  {
    slug: "bandai-channel",
    name: "Bandai Channel",
    url: "https://www.b-ch.com",
    status: "legal",
    kind: "stream",
    blurb: "Bandai's long-running Japanese anime streaming portal.",
    features: ["JP audio", "Catalog"],
    region: "Japan",
  },
  {
    slug: "niconico",
    name: "Niconico",
    url: "https://www.nicovideo.jp",
    status: "legal",
    kind: "stream",
    blurb: "Iconic Japanese video site with scrolling 'danmaku' comments and official anime channels.",
    features: ["JP audio", "Danmaku", "Community"],
    founded: 2006,
    region: "Japan",
  },
  {
    slug: "dmm-tv",
    name: "DMM TV",
    url: "https://tv.dmm.com",
    status: "legal",
    kind: "stream",
    blurb: "DMM's subscription VOD with a strong anime focus for the Japanese market.",
    features: ["JP audio", "Premium"],
    region: "Japan",
  },
  {
    slug: "lemino",
    name: "Lemino",
    url: "https://lemino.docomo.ne.jp",
    status: "legal",
    kind: "stream",
    blurb: "Docomo's general VOD service (the rebrand of dTV) with an anime catalog.",
    features: ["JP audio", "Free + premium"],
    region: "Japan",
  },
  {
    slug: "fod",
    name: "FOD (Fuji TV)",
    url: "https://fod.fujitv.co.jp",
    status: "legal",
    kind: "stream",
    blurb: "Fuji Television's on-demand platform, including its noitaminA anime block.",
    features: ["JP audio", "Broadcaster"],
    region: "Japan",
  },
  {
    slug: "hulu-japan",
    name: "Hulu Japan",
    url: "https://www.hulu.jp",
    status: "legal",
    kind: "stream",
    blurb: "Operated separately by NTV, with its own Japan-focused anime catalog.",
    features: ["JP audio"],
    region: "Japan",
  },

  // ----- Legal streaming: China -----
  {
    slug: "bilibili",
    name: "Bilibili",
    url: "https://www.bilibili.com",
    status: "legal",
    kind: "stream",
    blurb: "China's dominant video platform; licenses anime and produces donghua, with signature danmaku comments.",
    features: ["Subbed", "Danmaku", "Donghua"],
    founded: 2009,
    region: "Mainland China",
    emoji: "📺",
    gradient: "from-pink-500 to-rose-500",
  },
  {
    slug: "bstation",
    name: "Bstation (Bilibili SEA)",
    url: "https://www.bilibili.tv",
    status: "legal",
    kind: "stream",
    blurb: "Bilibili's overseas app legally simulcasting anime and donghua across Southeast Asia.",
    features: ["Subbed", "Simulcast", "Free tier"],
    region: "SE Asia",
    emoji: "🅱️",
    gradient: "from-pink-500 to-rose-500",
  },
  {
    slug: "iqiyi",
    name: "iQIYI",
    url: "https://www.iq.com",
    status: "legal",
    kind: "stream",
    blurb: "Major Chinese streamer; its international iQ.com app carries anime across Asia.",
    features: ["Subbed", "Donghua"],
    region: "China / SE Asia",
  },
  {
    slug: "tencent-video",
    name: "Tencent Video",
    url: "https://v.qq.com",
    status: "legal",
    kind: "stream",
    blurb: "One of China's largest streamers, with anime and original donghua.",
    features: ["Subbed", "Donghua"],
    region: "China",
  },
  {
    slug: "wetv",
    name: "WeTV",
    url: "https://wetv.vip",
    status: "legal",
    kind: "stream",
    blurb: "Tencent's international app streaming anime and donghua across Southeast Asia.",
    features: ["Subbed", "Donghua"],
    region: "SE Asia",
  },
  {
    slug: "youku",
    name: "Youku",
    url: "https://www.youku.com",
    status: "legal",
    kind: "stream",
    blurb: "Alibaba-owned Chinese video platform with licensed anime and donghua.",
    features: ["Subbed", "Donghua"],
    region: "China",
  },

  // ----- Legal streaming: Korea -----
  {
    slug: "laftel",
    name: "Laftel",
    url: "https://laftel.net",
    status: "legal",
    kind: "stream",
    blurb: "Popular Korean anime-only service with a deep simulcast catalog.",
    features: ["Subbed (KR)", "Simulcast"],
    founded: 2014,
    region: "South Korea",
    emoji: "🇰🇷",
    gradient: "from-purple-500 to-indigo-500",
  },
  {
    slug: "aniplus-korea",
    name: "Aniplus",
    url: "https://www.aniplustv.com",
    status: "legal",
    kind: "stream",
    blurb: "Korean anime channel and streamer with same-season simulcasts.",
    features: ["Subbed (KR)", "Simulcast", "Channel"],
    region: "South Korea",
  },
  {
    slug: "watcha",
    name: "Watcha",
    url: "https://watcha.com",
    status: "legal",
    kind: "stream",
    blurb: "Korean subscription VOD with a curated anime selection.",
    features: ["Subbed (KR)"],
    region: "South Korea",
  },
  {
    slug: "tving",
    name: "TVING",
    url: "https://www.tving.com",
    status: "legal",
    kind: "stream",
    blurb: "Major Korean streamer carrying licensed anime alongside K-content.",
    features: ["Subbed (KR)"],
    region: "South Korea",
  },

  // ----- Legal streaming: Taiwan / HK -----
  {
    slug: "ani-gamer",
    name: "Bahamut Anime Crazy (動畫瘋)",
    url: "https://ani.gamer.com.tw",
    status: "legal",
    kind: "stream",
    blurb: "Taiwan's hugely popular free/premium anime streamer from Gamer.com.tw.",
    features: ["Subbed (TW)", "Simulcast", "Free + premium"],
    region: "Taiwan",
  },
  {
    slug: "kktv",
    name: "KKTV",
    url: "https://www.kktv.me",
    status: "legal",
    kind: "stream",
    blurb: "Taiwanese VOD with simulcast anime among its drama catalog.",
    features: ["Subbed (TW)", "Simulcast"],
    region: "Taiwan",
  },
  {
    slug: "friday-video",
    name: "friDay Video",
    url: "https://video.friday.tw",
    status: "legal",
    kind: "stream",
    blurb: "FarEasTone's Taiwanese streaming service with an anime section.",
    features: ["Subbed (TW)"],
    region: "Taiwan",
  },

  // ----- Legal streaming: SE / South Asia -----
  {
    slug: "muse-asia",
    name: "Muse Asia",
    url: "https://www.youtube.com/@MuseAsia",
    status: "legal",
    kind: "stream",
    blurb: "Licensed YouTube channel legally simulcasting anime for free across South & Southeast Asia.",
    features: ["Free", "Subbed", "Simulcast", "YouTube"],
    founded: 2019,
    region: "S / SE Asia",
    emoji: "🎶",
    gradient: "from-fuchsia-500 to-pink-500",
  },
  {
    slug: "ani-one",
    name: "Ani-One Asia",
    url: "https://www.youtube.com/@Ani-OneAsia",
    status: "legal",
    kind: "stream",
    blurb: "Medialink's licensed YouTube channel with free and 'Ultra' membership simulcasts for Asia.",
    features: ["Free + membership", "Subbed", "YouTube"],
    founded: 2020,
    region: "Asia",
    emoji: "🇦",
    gradient: "from-teal-400 to-cyan-500",
  },
  {
    slug: "iqiyi-intl",
    name: "iQIYI International",
    url: "https://www.iq.com",
    status: "legal",
    kind: "stream",
    blurb: "iQIYI's overseas app with simulcast anime for Southeast Asian viewers.",
    features: ["Subbed", "Simulcast"],
    region: "SE Asia",
  },
  {
    slug: "vidio",
    name: "Vidio",
    url: "https://www.vidio.com",
    status: "legal",
    kind: "stream",
    blurb: "Indonesia's leading streamer with a licensed anime catalog.",
    features: ["Subbed (ID)"],
    region: "Indonesia",
  },
  {
    slug: "viu",
    name: "Viu",
    url: "https://www.viu.com",
    status: "legal",
    kind: "stream",
    blurb: "PCCW's pan-Asian streamer carrying licensed anime alongside Asian dramas.",
    features: ["Subbed", "Free + premium"],
    region: "Asia / MENA",
  },
  {
    slug: "catchplay",
    name: "CATCHPLAY+",
    url: "https://www.catchplay.com",
    status: "legal",
    kind: "stream",
    blurb: "Southeast Asian streaming service with a selection of licensed anime.",
    features: ["Subbed"],
    region: "SE Asia",
  },
  {
    slug: "disney-hotstar",
    name: "Disney+ Hotstar",
    url: "https://www.hotstar.com",
    status: "legal",
    kind: "stream",
    blurb: "Disney's South/Southeast Asian platform carrying licensed anime.",
    features: ["Subbed", "Dubbed"],
    region: "S / SE Asia",
  },

  // ----- Legal streaming: Europe -----
  {
    slug: "adn-fr",
    name: "Animation Digital Network (FR)",
    url: "https://animationdigitalnetwork.fr",
    status: "legal",
    kind: "stream",
    blurb: "The leading French-language simulcast streamer (France, Belgium, Luxembourg).",
    features: ["Subbed (FR)", "Dubbed (FR)", "Simulcast"],
    region: "France / Belgium",
    emoji: "🇫🇷",
    gradient: "from-blue-500 to-violet-500",
  },
  {
    slug: "adn-de",
    name: "Animation Digital Network (DE)",
    url: "https://animationdigitalnetwork.de",
    status: "legal",
    kind: "stream",
    blurb: "ADN's German-language simulcast service for Germany and Austria.",
    features: ["Subbed (DE)", "Simulcast"],
    region: "Germany / Austria",
  },
  {
    slug: "vvvvid",
    name: "VVVVID",
    url: "https://www.vvvvid.it",
    status: "legal",
    kind: "stream",
    blurb: "Free, ad-supported Italian streamer with a strong licensed anime catalog.",
    features: ["Free w/ ads", "Subbed (IT)", "Dubbed (IT)"],
    region: "Italy",
  },
  {
    slug: "anime-generation",
    name: "Anime Generation",
    url: "https://www.primevideo.com",
    status: "legal",
    kind: "stream",
    blurb: "Italian anime channel (via Prime Video) from Yamato Video / Anime Factory.",
    features: ["Subbed (IT)", "Dubbed (IT)", "Channel"],
    region: "Italy",
  },
  {
    slug: "selecta-vision",
    name: "Selecta Visión",
    url: "https://shop.selecta-vision.com",
    status: "legal",
    kind: "stream",
    blurb: "Spanish distributor whose platform simulcasts anime for Spain.",
    features: ["Subbed (ES)", "Simulcast"],
    region: "Spain",
  },
  {
    slug: "akiba-pass",
    name: "AKIBA PASS TV",
    url: "https://akibapasstv.vhx.tv",
    status: "legal",
    kind: "stream",
    blurb: "German-region anime streamer from AV Visionen.",
    features: ["Subbed (DE)"],
    region: "Germany / Austria",
  },
  {
    slug: "prosieben-maxx",
    name: "ProSieben Maxx",
    url: "https://www.prosiebenmaxx.de",
    status: "legal",
    kind: "stream",
    blurb: "German free-TV channel with a long-running anime block and online streams.",
    features: ["Dubbed (DE)", "Broadcaster"],
    region: "Germany",
  },

  // ----- Legal streaming: Latin America / MENA / Russia -----
  {
    slug: "anime-onegai",
    name: "Anime Onegai",
    url: "https://www.animeonegai.com",
    status: "legal",
    kind: "stream",
    blurb: "Latin-American legal streamer backed by Japanese studios, with Spanish/Portuguese simulcasts.",
    features: ["Subbed (ES/PT)", "Dubbed", "Simulcast"],
    founded: 2021,
    region: "Latin America",
    emoji: "🌎",
    gradient: "from-emerald-400 to-teal-500",
  },
  {
    slug: "starzplay",
    name: "STARZPLAY",
    url: "https://www.starzplay.com",
    status: "legal",
    kind: "stream",
    blurb: "MENA-region streamer carrying licensed anime alongside Western content.",
    features: ["Subbed", "Dubbed"],
    region: "MENA",
  },
  {
    slug: "shahid",
    name: "Shahid",
    url: "https://shahid.mbc.net",
    status: "legal",
    kind: "stream",
    blurb: "MBC's leading Arabic-region streamer with an anime selection.",
    features: ["Subbed (AR)", "Dubbed (AR)"],
    region: "Arab world",
  },
  {
    slug: "okko",
    name: "Okko",
    url: "https://okko.tv",
    status: "legal",
    kind: "stream",
    blurb: "Russian VOD service that licenses anime for the local market.",
    features: ["Subbed (RU)", "Dubbed (RU)"],
    region: "Russia",
  },
  {
    slug: "wakanim-yt",
    name: "Crunchyroll Channel (YouTube)",
    url: "https://www.youtube.com/@Crunchyroll",
    status: "legal",
    kind: "stream",
    blurb: "Official YouTube presence with free episodes, dubs, and clips.",
    features: ["Free", "Clips", "YouTube"],
    region: "Worldwide",
  },
  {
    slug: "animelog",
    name: "AnimeLog (アニメログ)",
    url: "https://www.youtube.com/@animelogtv",
    status: "legal",
    kind: "stream",
    blurb: "Industry-backed YouTube channel streaming classic anime free worldwide.",
    features: ["Free", "Classic", "YouTube"],
    region: "Worldwide",
  },

  // =========================================================================
  // LEGAL — manga & light novels
  // =========================================================================
  {
    slug: "manga-plus",
    name: "MANGA Plus by Shueisha",
    url: "https://mangaplus.shueisha.co.jp",
    status: "legal",
    kind: "manga",
    blurb: "Shueisha's official app — latest Shonen Jump chapters free, same day as Japan.",
    features: ["Official", "Free", "Simulpub", "Multi-language"],
    founded: 2019,
    region: "Worldwide (most)",
    emoji: "➕",
    gradient: "from-red-500 to-rose-600",
    featured: true,
  },
  {
    slug: "viz",
    name: "VIZ / Shonen Jump",
    url: "https://www.viz.com",
    status: "legal",
    kind: "manga",
    blurb: "VIZ Media's official reader; a cheap Shonen Jump membership unlocks a huge English vault.",
    features: ["Official", "Membership", "English"],
    founded: 1986,
    region: "US / CA",
    emoji: "📚",
    gradient: "from-blue-500 to-violet-500",
  },
  {
    slug: "k-manga",
    name: "K MANGA",
    url: "https://kmanga.kodansha.com",
    status: "legal",
    kind: "manga",
    blurb: "Kodansha's official US app for simulpub manga (Blue Lock, Attack on Titan catalog).",
    features: ["Official", "Simulpub", "Tickets"],
    founded: 2023,
    region: "United States",
  },
  {
    slug: "manga-up",
    name: "Manga UP! Global",
    url: "https://global.manga-up.com",
    status: "legal",
    kind: "manga",
    blurb: "Square Enix's official global app for its manga catalog.",
    features: ["Official", "Free + points"],
    region: "Worldwide (most)",
  },
  {
    slug: "comic-walker",
    name: "ComicWalker",
    url: "https://comic-walker.com",
    status: "legal",
    kind: "manga",
    blurb: "Kadokawa's official free reader, spanning manga in Japanese and other languages.",
    features: ["Official", "Free"],
    region: "Worldwide",
  },
  {
    slug: "azuki",
    name: "Azuki",
    url: "https://www.azuki.co",
    status: "legal",
    kind: "manga",
    blurb: "Subscription manga service with a clean reader and a growing licensed catalog.",
    features: ["Official", "Subscription"],
    region: "Worldwide (most)",
  },
  {
    slug: "inkr",
    name: "INKR",
    url: "https://comics.inkr.com",
    status: "legal",
    kind: "manga",
    blurb: "Manga/manhwa/manhua platform with smart-panel reading and licensed titles.",
    features: ["Official", "Smart panels"],
    region: "Worldwide",
  },
  {
    slug: "comikey",
    name: "Comikey",
    url: "https://comikey.com",
    status: "legal",
    kind: "manga",
    blurb: "Simulpub manga/manhwa/manhua publisher with free-to-wait reading.",
    features: ["Official", "Simulpub", "Free-to-wait"],
    region: "Worldwide",
  },
  {
    slug: "mangamo",
    name: "Mangamo",
    url: "https://www.mangamo.com",
    status: "legal",
    kind: "manga",
    blurb: "All-you-can-read manga subscription app with licensed titles.",
    features: ["Official", "Subscription"],
    region: "US / CA",
  },
  {
    slug: "bookwalker",
    name: "BookWalker Global",
    url: "https://global.bookwalker.jp",
    status: "legal",
    kind: "manga",
    blurb: "Kadokawa's global storefront for digital manga and light novels.",
    features: ["Official", "Store", "Light novels"],
    region: "Worldwide",
  },
  {
    slug: "yen-press",
    name: "Yen Press",
    url: "https://yenpress.com",
    status: "legal",
    kind: "manga",
    blurb: "Major English manga/LN publisher with its own digital store.",
    features: ["Official", "Store"],
    region: "Worldwide (most)",
  },
  {
    slug: "mangaplaza",
    name: "MangaPlaza",
    url: "https://mangaplaza.com",
    status: "legal",
    kind: "manga",
    blurb: "Official North American reader from NTT Solmare with a large licensed catalog.",
    features: ["Official", "Free + points"],
    region: "North America",
  },
  {
    slug: "webtoon",
    name: "WEBTOON",
    url: "https://www.webtoons.com",
    status: "legal",
    kind: "manga",
    blurb: "The dominant vertical-scroll comics platform; mostly manhwa/originals with some manga.",
    features: ["Official", "Free + coins", "Webtoons"],
    region: "Worldwide",
  },
  {
    slug: "tapas",
    name: "Tapas",
    url: "https://tapas.io",
    status: "legal",
    kind: "manga",
    blurb: "Webcomics and novels platform (Kakao-owned) with licensed and original series.",
    features: ["Official", "Free-to-wait"],
    region: "Worldwide",
  },
  {
    slug: "tappytoon",
    name: "Tappytoon",
    url: "https://www.tappytoon.com",
    status: "legal",
    kind: "manga",
    blurb: "Officially licensed manhwa and manga with simultaneous English releases.",
    features: ["Official", "Manhwa"],
    region: "Worldwide (most)",
  },
  {
    slug: "lezhin",
    name: "Lezhin Comics",
    url: "https://www.lezhinus.com",
    status: "legal",
    kind: "manga",
    blurb: "Premium licensed manhwa platform with same-day English releases.",
    features: ["Official", "Manhwa", "Premium"],
    region: "Worldwide (most)",
  },
  {
    slug: "manta",
    name: "Manta",
    url: "https://manta.net",
    status: "legal",
    kind: "manga",
    blurb: "All-you-can-read manhwa subscription from Ridi.",
    features: ["Official", "Subscription", "Manhwa"],
    region: "Worldwide (most)",
  },
  {
    slug: "renta",
    name: "Renta!",
    url: "https://www.ebookrenta.com",
    status: "legal",
    kind: "manga",
    blurb: "NTT Solmare's official manga rental/purchase store in English.",
    features: ["Official", "Rent / buy"],
    region: "Worldwide (most)",
  },

  // =========================================================================
  // LEGAL — databases, trackers & news
  // =========================================================================
  {
    slug: "myanimelist",
    name: "MyAnimeList",
    url: "https://myanimelist.net",
    status: "legal",
    kind: "database",
    blurb: "The default anime/manga database and tracker — scores, seasonal charts, and lists for everything.",
    features: ["Tracking", "Database", "Community"],
    founded: 2004,
    region: "Worldwide",
    emoji: "📊",
    gradient: "from-indigo-500 to-violet-600",
    featured: true,
  },
  {
    slug: "anilist",
    name: "AniList",
    url: "https://anilist.co",
    status: "legal",
    kind: "database",
    blurb: "Modern, fast tracker and database with rich stats, a social feed, and a public GraphQL API.",
    features: ["Tracking", "API", "Social"],
    founded: 2014,
    region: "Worldwide",
    emoji: "📈",
    gradient: "from-cyan-400 to-blue-500",
  },
  {
    slug: "kitsu",
    name: "Kitsu",
    url: "https://kitsu.app",
    status: "legal",
    kind: "database",
    blurb: "Open, community tracker and database with a friendly UI and an open API.",
    features: ["Tracking", "API", "Open"],
    region: "Worldwide",
  },
  {
    slug: "anidb",
    name: "AniDB",
    url: "https://anidb.net",
    status: "legal",
    kind: "database",
    blurb: "Veteran, extremely detailed database — the canonical source for episode and release metadata.",
    features: ["Database", "Metadata"],
    founded: 2003,
    region: "Worldwide",
  },
  {
    slug: "anime-planet",
    name: "Anime-Planet",
    url: "https://www.anime-planet.com",
    status: "legal",
    kind: "database",
    blurb: "Recommendation-focused database and tracker that links out to legal streams.",
    features: ["Tracking", "Recommendations", "Legal links"],
    founded: 2001,
    region: "Worldwide",
  },
  {
    slug: "mangaupdates",
    name: "Baka-Updates Manga",
    url: "https://www.mangaupdates.com",
    status: "legal",
    kind: "database",
    blurb: "The reference database for manga releases, scanlation groups, and series info.",
    features: ["Database", "Releases", "Tracking"],
    region: "Worldwide",
  },
  {
    slug: "livechart",
    name: "LiveChart.me",
    url: "https://www.livechart.me",
    status: "legal",
    kind: "schedule",
    blurb: "Slick seasonal anime chart and countdown with streaming-availability info.",
    features: ["Seasonal", "Countdowns", "Where to watch"],
    region: "Worldwide",
  },
  {
    slug: "notify-moe",
    name: "Notify.moe",
    url: "https://notify.moe",
    status: "legal",
    kind: "database",
    blurb: "Open-source anime tracker and notifier with a fast, minimalist interface.",
    features: ["Tracking", "Notifications", "Open"],
    region: "Worldwide",
  },
  {
    slug: "shikimori",
    name: "Shikimori",
    url: "https://shikimori.one",
    status: "legal",
    kind: "database",
    blurb: "The leading Russian-language anime/manga database and tracking community.",
    features: ["Tracking", "Database", "RU"],
    region: "Russia / CIS",
  },
  {
    slug: "annict",
    name: "Annict",
    url: "https://annict.com",
    status: "legal",
    kind: "database",
    blurb: "Japanese-built anime tracker focused on logging what you watch each season.",
    features: ["Tracking", "JP"],
    region: "Japan / Worldwide",
  },
  {
    slug: "simkl",
    name: "Simkl",
    url: "https://simkl.com",
    status: "legal",
    kind: "database",
    blurb: "Cross-media tracker (TV, film, anime) with automatic scrobbling and where-to-watch.",
    features: ["Tracking", "Scrobbling"],
    region: "Worldwide",
  },
  {
    slug: "because-moe",
    name: "because.moe",
    url: "https://because.moe",
    status: "legal",
    kind: "database",
    blurb: "Tells you where a given anime is legally streaming in your country.",
    features: ["Where to watch", "Legal"],
    region: "Worldwide",
  },
  {
    slug: "anime-news-network",
    name: "Anime News Network",
    url: "https://www.animenewsnetwork.com",
    status: "legal",
    kind: "news",
    blurb: "The industry's news outlet of record — announcements, reviews, and an encyclopedia.",
    features: ["News", "Reviews", "Encyclopedia"],
    founded: 1998,
    region: "Worldwide",
    emoji: "📰",
    gradient: "from-sky-500 to-indigo-500",
  },
  {
    slug: "anime-trending",
    name: "Anime Trending",
    url: "https://www.anitrendz.com",
    status: "legal",
    kind: "news",
    blurb: "Community polls, rankings, and news that track what's popular each season.",
    features: ["News", "Polls", "Rankings"],
    region: "Worldwide",
  },
  {
    slug: "anime-corner",
    name: "Anime Corner",
    url: "https://animecorner.me",
    status: "legal",
    kind: "news",
    blurb: "Fast-moving news, weekly rankings, and industry coverage.",
    features: ["News", "Rankings"],
    region: "Worldwide",
  },
  {
    slug: "otaku-usa",
    name: "Otaku USA",
    url: "https://otakuusamagazine.com",
    status: "legal",
    kind: "news",
    blurb: "Long-running English anime/manga magazine and news site.",
    features: ["News", "Features"],
    region: "North America",
  },
  {
    slug: "honeys-anime",
    name: "Honey's Anime",
    url: "https://honeysanime.com",
    status: "legal",
    kind: "news",
    blurb: "News, recommendation lists, and reviews aimed at international fans.",
    features: ["News", "Lists", "Reviews"],
    region: "Worldwide",
  },

  // =========================================================================
  // FREE / UNOFFICIAL — streaming (active)
  // =========================================================================
  {
    slug: "gogoanime",
    name: "Gogoanime",
    status: "free",
    kind: "stream",
    blurb: "Long-running free streaming brand that survives through endless clones and mirror domains.",
    features: ["Subbed", "Dubbed", "Many clones"],
    region: "Worldwide",
    blockedIn: ["India", "Australia", "UK"],
    emoji: "🟢",
    gradient: "from-lime-400 to-emerald-500",
    featured: true,
  },
  {
    slug: "animepahe",
    name: "AnimePahe",
    status: "free",
    kind: "stream",
    blurb: "Free streamer favored for small file sizes, downloads, and one of the larger dub libraries.",
    features: ["Subbed", "Dubbed", "Downloads", "Small files"],
    region: "Worldwide",
    blockedIn: ["India"],
    emoji: "🥧",
    gradient: "from-amber-400 to-orange-500",
  },
  {
    slug: "allanime",
    name: "AllAnime",
    status: "free",
    kind: "stream",
    blurb: "Free library with a public API, widely used as a back-end for community apps and CLIs.",
    features: ["Subbed", "Dubbed", "API", "CLI-friendly"],
    region: "Worldwide",
  },
  {
    slug: "miruro",
    name: "Miruro",
    status: "free",
    kind: "stream",
    blurb: "Sleek modern front-end aggregating free streams with AniList sync and a polished player.",
    features: ["Subbed", "Dubbed", "AniList sync"],
    region: "Worldwide",
  },
  {
    slug: "animekai",
    name: "AnimeKai",
    status: "free",
    kind: "stream",
    blurb: "Newer free streamer that gained traction as older aggregators shut down.",
    features: ["Subbed", "Dubbed"],
    region: "Worldwide",
  },
  {
    slug: "anix",
    name: "Anix",
    status: "free",
    kind: "stream",
    blurb: "Free streaming aggregator with a clean catalog and multiple player sources.",
    features: ["Subbed", "Dubbed"],
    region: "Worldwide",
  },
  {
    slug: "animeowl",
    name: "AnimeOwl",
    status: "free",
    kind: "stream",
    blurb: "Free streamer offering dual-audio releases and high-bitrate options.",
    features: ["Subbed", "Dubbed", "Dual-audio"],
    region: "Worldwide",
  },
  {
    slug: "kaido",
    name: "Kaido",
    status: "free",
    kind: "stream",
    blurb: "Zoro-style free streaming front-end that emerged amid the aggregator churn.",
    features: ["Subbed", "Dubbed"],
    region: "Worldwide",
  },
  {
    slug: "hikari",
    name: "Hikari",
    status: "free",
    kind: "stream",
    blurb: "Minimalist free streamer with AniList/MAL integration.",
    features: ["Subbed", "Dubbed", "Tracker sync"],
    region: "Worldwide",
  },
  {
    slug: "anizone",
    name: "AniZone",
    status: "free",
    kind: "stream",
    blurb: "Free streaming aggregator with a large searchable catalog.",
    features: ["Subbed", "Dubbed"],
    region: "Worldwide",
  },
  {
    slug: "animedao",
    name: "AnimeDao",
    status: "free",
    kind: "stream",
    blurb: "Veteran free streamer known for low-bandwidth playback; lives on through mirrors.",
    features: ["Subbed", "Low bandwidth"],
    region: "Worldwide",
  },
  {
    slug: "animesuge",
    name: "AnimeSuge",
    status: "free",
    kind: "stream",
    blurb: "Free streaming aggregator with a broad library and frequent domain changes.",
    features: ["Subbed", "Dubbed", "Domain-hops"],
    region: "Worldwide",
  },
  {
    slug: "animeflix",
    name: "AnimeFlix",
    status: "free",
    kind: "stream",
    blurb: "Free streamer with a Netflix-style UI; one of several reusing the AnimeFlix name.",
    features: ["Subbed", "Dubbed"],
    region: "Worldwide",
  },
  {
    slug: "yugenanime",
    name: "YugenAnime",
    status: "free",
    kind: "stream",
    blurb: "Community-favored free streamer with a clean, ad-light interface.",
    features: ["Subbed", "Ad-light"],
    region: "Worldwide",
  },
  {
    slug: "kawaiifu",
    name: "Kawaiifu",
    status: "free",
    kind: "stream",
    blurb: "Free streamer offering higher-quality encodes and download options.",
    features: ["Subbed", "Downloads", "HD"],
    region: "Worldwide",
  },
  {
    slug: "anitaku",
    name: "Anitaku",
    status: "free",
    kind: "stream",
    blurb: "One of the primary domains the Gogoanime brand has operated under.",
    features: ["Subbed", "Dubbed", "Gogo family"],
    region: "Worldwide",
  },

  // ----- Free streaming: Spanish / Latin America -----
  {
    slug: "animeflv",
    name: "AnimeFLV",
    status: "free",
    kind: "stream",
    blurb: "The dominant Spanish-language free streaming site for Latin America, around for over a decade.",
    features: ["Subbed (ES)", "Latam", "Veteran"],
    region: "Latin America",
    blockedIn: ["Spain"],
    emoji: "🇪🇸",
    gradient: "from-rose-500 to-orange-400",
  },
  {
    slug: "jkanime",
    name: "Jkanime",
    status: "free",
    kind: "stream",
    blurb: "Popular Spanish-language free streamer with a large catalog.",
    features: ["Subbed (ES)", "Latam"],
    region: "Latin America",
  },
  {
    slug: "monoschinos",
    name: "MonosChinos",
    status: "free",
    kind: "stream",
    blurb: "Spanish-language free streamer with simulcast subs and dubs.",
    features: ["Subbed (ES)", "Dubbed (ES)"],
    region: "Latin America",
  },
  {
    slug: "tioanime",
    name: "TioAnime",
    status: "free",
    kind: "stream",
    blurb: "Lightweight Spanish-language free streaming site.",
    features: ["Subbed (ES)"],
    region: "Latin America",
  },
  {
    slug: "animefenix",
    name: "AnimeFénix",
    status: "free",
    kind: "stream",
    blurb: "Spanish-language free streamer with multiple player mirrors.",
    features: ["Subbed (ES)"],
    region: "Latin America",
  },
  {
    slug: "otakustv",
    name: "OtakusTV",
    status: "free",
    kind: "stream",
    blurb: "Spanish-language free streamer offering subs and Latin dubs.",
    features: ["Subbed (ES)", "Dubbed (ES)"],
    region: "Latin America",
  },

  // ----- Free streaming: Portuguese / Brazil -----
  {
    slug: "anroll",
    name: "AnRoll",
    status: "free",
    kind: "stream",
    blurb: "One of Brazil's most-used free anime streamers.",
    features: ["Subbed (PT)", "Dubbed (PT)"],
    region: "Brazil",
  },
  {
    slug: "betteranime",
    name: "BetterAnime",
    status: "free",
    kind: "stream",
    blurb: "Brazilian free streamer with subbed and Portuguese-dubbed catalogs.",
    features: ["Subbed (PT)", "Dubbed (PT)"],
    region: "Brazil",
  },
  {
    slug: "goyabu",
    name: "Goyabu",
    status: "free",
    kind: "stream",
    blurb: "Long-standing Brazilian free anime streaming site.",
    features: ["Subbed (PT)", "Dubbed (PT)"],
    region: "Brazil",
  },
  {
    slug: "animefire",
    name: "AnimeFire",
    status: "free",
    kind: "stream",
    blurb: "Brazilian free streamer popular for fast releases.",
    features: ["Subbed (PT)", "Dubbed (PT)"],
    region: "Brazil",
  },

  // ----- Free streaming: French / German / Arabic / Russian -----
  {
    slug: "anime-sama",
    name: "Anime-Sama",
    status: "free",
    kind: "stream",
    blurb: "The largest French-language free streaming catalog.",
    features: ["Subbed (FR)", "Dubbed (FR)"],
    region: "France",
  },
  {
    slug: "voiranime",
    name: "VoirAnime",
    status: "free",
    kind: "stream",
    blurb: "Popular French-language free streamer; frequently changes domains.",
    features: ["Subbed (FR)", "Domain-hops"],
    region: "France",
    blockedIn: ["France"],
  },
  {
    slug: "aniworld",
    name: "AniWorld",
    status: "free",
    kind: "stream",
    blurb: "The major German-language free streaming site.",
    features: ["Subbed (DE)", "Dubbed (DE)"],
    region: "Germany",
    blockedIn: ["Germany"],
  },
  {
    slug: "animeworld-it",
    name: "AnimeWorld (IT)",
    status: "free",
    kind: "stream",
    blurb: "The dominant Italian-language free streaming site.",
    features: ["Subbed (IT)", "Dubbed (IT)"],
    region: "Italy",
    blockedIn: ["Italy"],
  },
  {
    slug: "anime4up",
    name: "Anime4up",
    status: "free",
    kind: "stream",
    blurb: "One of the most-used Arabic-language free anime streamers.",
    features: ["Subbed (AR)"],
    region: "Arab world",
  },
  {
    slug: "witanime",
    name: "WitAnime",
    status: "free",
    kind: "stream",
    blurb: "Arabic-language free streaming aggregator with multiple mirrors.",
    features: ["Subbed (AR)"],
    region: "Arab world",
  },
  {
    slug: "animego",
    name: "AnimeGO",
    status: "free",
    kind: "stream",
    blurb: "Large Russian-language free streamer.",
    features: ["Subbed (RU)", "Dubbed (RU)"],
    region: "Russia / CIS",
  },
  {
    slug: "jutsu",
    name: "Jut.su",
    status: "free",
    kind: "stream",
    blurb: "Veteran Russian-language free anime site.",
    features: ["Subbed (RU)", "Dubbed (RU)"],
    region: "Russia / CIS",
  },
  {
    slug: "sovetromantica",
    name: "SovetRomantica",
    status: "free",
    kind: "stream",
    blurb: "Russian fansub community and streamer known for its own subtitle releases.",
    features: ["Subbed (RU)", "Fansubs"],
    region: "Russia / CIS",
  },
  {
    slug: "animevost",
    name: "AnimeVost",
    status: "free",
    kind: "stream",
    blurb: "Russian-language free streamer with its own voiceover dubs.",
    features: ["Dubbed (RU)"],
    region: "Russia / CIS",
  },

  // =========================================================================
  // FREE / UNOFFICIAL — manga & manhwa
  // =========================================================================
  {
    slug: "mangadex",
    name: "MangaDex",
    status: "free",
    kind: "manga",
    blurb: "Ad-free, community-run scanlation aggregator with a strong API and many languages.",
    features: ["Scanlations", "Ad-free", "API", "Multi-language"],
    founded: 2018,
    region: "Worldwide",
    emoji: "📖",
    gradient: "from-blue-500 to-violet-500",
    featured: true,
  },
  {
    slug: "comick",
    name: "Comick",
    status: "free",
    kind: "manga",
    blurb: "Fast, ad-light scanlation aggregator with tracker integration; a common MangaDex alternative.",
    features: ["Scanlations", "Ad-light", "Tracker sync"],
    region: "Worldwide",
  },
  {
    slug: "mangafire",
    name: "MangaFire",
    status: "free",
    kind: "manga",
    blurb: "Polished free reader with a large library, from the team behind the AnimeFire-style sites.",
    features: ["Scanlations", "Modern UI"],
    region: "Worldwide",
  },
  {
    slug: "weebcentral",
    name: "Weeb Central",
    status: "free",
    kind: "manga",
    blurb: "Free reader that rose as a successor when MangaSee/Manga4Life went dark.",
    features: ["Scanlations", "Successor"],
    region: "Worldwide",
  },
  {
    slug: "batoto",
    name: "Bato.to",
    status: "free",
    kind: "manga",
    blurb: "Community manga reader (revived from the original Batoto) with group-friendly features.",
    features: ["Scanlations", "Community", "Multi-language"],
    region: "Worldwide",
  },
  {
    slug: "mangapark",
    name: "MangaPark",
    status: "free",
    kind: "manga",
    blurb: "Large free reader aggregating scanlations with multiple source mirrors.",
    features: ["Scanlations", "Large library"],
    region: "Worldwide",
  },
  {
    slug: "mangakakalot",
    name: "Mangakakalot",
    status: "free",
    kind: "manga",
    blurb: "Veteran free manga reader, part of the sprawling Kakalot/Nato family of sites.",
    features: ["Free", "Large library"],
    region: "Worldwide",
  },
  {
    slug: "natomanga",
    name: "Natomanga (ex-Manganato)",
    status: "free",
    kind: "manga",
    blurb: "Manganato/Nelomanga lineage of free readers; rebrands and shifts domains over time.",
    features: ["Free", "Domain-hops"],
    region: "Worldwide",
  },
  {
    slug: "mangabuddy",
    name: "MangaBuddy",
    status: "free",
    kind: "manga",
    blurb: "Free reader with a broad catalog of manga, manhwa, and manhua.",
    features: ["Free", "Manhwa", "Manhua"],
    region: "Worldwide",
  },
  {
    slug: "mangareader",
    name: "MangaReader",
    status: "free",
    kind: "manga",
    blurb: "Free reader (mangareader.to) with a clean UI and dual-language options.",
    features: ["Free", "Multi-language"],
    region: "Worldwide",
  },
  {
    slug: "mangakatana",
    name: "MangaKatana",
    status: "free",
    kind: "manga",
    blurb: "Lightweight free reader popular for fast loading and minimal ads.",
    features: ["Free", "Fast"],
    region: "Worldwide",
  },
  {
    slug: "mangapill",
    name: "Mangapill",
    status: "free",
    kind: "manga",
    blurb: "Simple, fast free reader with a focus on shounen series.",
    features: ["Free", "Fast"],
    region: "Worldwide",
  },
  {
    slug: "asurascans",
    name: "Asura Scans",
    status: "free",
    kind: "manga",
    blurb: "Prominent scanlation group and reader specializing in popular manhwa.",
    features: ["Scanlations", "Manhwa"],
    region: "Worldwide",
  },
  {
    slug: "flamecomics",
    name: "Flame Comics",
    status: "free",
    kind: "manga",
    blurb: "Scanlation group and reader known for action manhwa releases.",
    features: ["Scanlations", "Manhwa"],
    region: "Worldwide",
  },
  {
    slug: "reaperscans",
    name: "Reaper Scans",
    status: "free",
    kind: "manga",
    blurb: "Well-known scanlation group/reader for manhwa and manga.",
    features: ["Scanlations", "Manhwa"],
    region: "Worldwide",
  },
  {
    slug: "toonily",
    name: "Toonily",
    status: "free",
    kind: "manga",
    blurb: "Free manhwa-focused reader with a large webtoon catalog.",
    features: ["Free", "Manhwa", "Webtoons"],
    region: "Worldwide",
  },
  {
    slug: "mangago",
    name: "MangaGo",
    status: "free",
    kind: "manga",
    blurb: "Long-running free reader with a deep back catalog, popular for shoujo/BL.",
    features: ["Free", "Large library"],
    region: "Worldwide",
  },
  {
    slug: "dynasty-scans",
    name: "Dynasty Scans",
    status: "free",
    kind: "manga",
    blurb: "Specialist scanlation reader focused on yuri and doujin works.",
    features: ["Scanlations", "Yuri", "Doujin"],
    region: "Worldwide",
  },
  {
    slug: "cubari",
    name: "Cubari",
    status: "free",
    kind: "manga",
    blurb: "Image-proxy reader that renders manga from links without hosting anything itself.",
    features: ["Proxy reader", "No hosting"],
    region: "Worldwide",
  },
  {
    slug: "fanfox",
    name: "MangaFox (FanFox)",
    status: "free",
    kind: "manga",
    blurb: "Veteran free manga brand still operating as fanfox.net.",
    features: ["Free", "Veteran"],
    region: "Worldwide",
  },
  {
    slug: "mangahere",
    name: "MangaHere",
    status: "free",
    kind: "manga",
    blurb: "Long-running free manga reader, a sister to the MangaFox lineage.",
    features: ["Free", "Veteran"],
    region: "Worldwide",
  },

  // =========================================================================
  // FREE / UNOFFICIAL — downloads & torrents
  // =========================================================================
  {
    slug: "nyaa",
    name: "Nyaa",
    status: "free",
    kind: "download",
    blurb: "The central public BitTorrent index for fansubs and raws — backbone of the anime torrent scene.",
    features: ["Torrents", "Fansubs", "Raws", "Index"],
    region: "Worldwide",
    blockedIn: ["UK", "Australia", "Finland"],
    emoji: "🐱",
    gradient: "from-cyan-400 to-blue-500",
    featured: true,
  },
  {
    slug: "animetosho",
    name: "AnimeTosho",
    status: "free",
    kind: "download",
    blurb: "Mirror/index of anime torrents with direct-download links and rich metadata layered on Nyaa.",
    features: ["DDL", "Index", "Metadata"],
    region: "Worldwide",
  },
  {
    slug: "tokyo-toshokan",
    name: "Tokyo Toshokan",
    status: "free",
    kind: "download",
    blurb: "Veteran torrent/index tracker for anime, manga, music, and more.",
    features: ["Torrents", "Index", "Veteran"],
    region: "Worldwide",
  },
  {
    slug: "subsplease",
    name: "SubsPlease",
    status: "free",
    kind: "download",
    blurb: "Active release group posting fast, consistent weekly subs; successor to HorribleSubs.",
    features: ["Torrents", "Weekly", "Fast subs"],
    region: "Worldwide",
    successor: "Replaced HorribleSubs (2020)",
  },
  {
    slug: "erai-raws",
    name: "Erai-raws",
    status: "free",
    kind: "download",
    blurb: "Popular release group providing multi-subtitle weekly releases.",
    features: ["Torrents", "Multi-sub", "Weekly"],
    region: "Worldwide",
  },
  {
    slug: "anidex",
    name: "AniDex",
    status: "free",
    kind: "download",
    blurb: "Public torrent index and tracker, an alternative to Nyaa.",
    features: ["Torrents", "Index"],
    region: "Worldwide",
  },
  {
    slug: "acgnx",
    name: "AcgnX (ACG.RIP)",
    status: "free",
    kind: "download",
    blurb: "Chinese-community torrent index for anime, comics, and games.",
    features: ["Torrents", "Index", "CN"],
    region: "Worldwide",
  },
  {
    slug: "kayoanime",
    name: "Kayoanime",
    status: "free",
    kind: "download",
    blurb: "Direct-download (Google Drive) blog offering batch anime downloads.",
    features: ["DDL", "Batches"],
    region: "Worldwide",
  },
  {
    slug: "seadex",
    name: "SeaDex",
    status: "free",
    kind: "download",
    blurb: "Curated database pointing to the 'best' release of each title for collectors.",
    features: ["Release guide", "Curation"],
    region: "Worldwide",
  },
  {
    slug: "animebytes",
    name: "AnimeBytes",
    status: "free",
    kind: "download",
    blurb: "Invite-only private tracker, regarded as the gold standard for anime archival.",
    features: ["Private tracker", "Invite-only", "Archival"],
    region: "Worldwide",
  },
  {
    slug: "bakabt",
    name: "BakaBT",
    status: "free",
    kind: "download",
    blurb: "Curated semi-private tracker focused on complete, high-quality batches.",
    features: ["Semi-private", "Curated", "Batches"],
    region: "Worldwide",
  },

  // =========================================================================
  // SHUT DOWN / DEFUNCT
  // =========================================================================
  {
    slug: "funimation",
    name: "Funimation",
    status: "shutdown",
    kind: "stream",
    blurb: "The legendary dub powerhouse and streamer. After Sony's buyout, it folded entirely into Crunchyroll.",
    features: ["Was: Dubbed", "Was: Simulcast"],
    founded: 1994,
    endedYear: 2024,
    successor: "Merged into Crunchyroll",
    emoji: "🎬",
    gradient: "from-violet-500 to-fuchsia-500",
    featured: true,
  },
  {
    slug: "hianime",
    name: "HiAnime (ex-Zoro / aniwatch)",
    status: "shutdown",
    kind: "stream",
    blurb: "The biggest free streamer of its era. Went offline in early 2026 after a US 'Notorious Markets' listing; clones using the name are unsafe.",
    features: ["Was: Subbed", "Was: Dubbed", "Name abused by clones"],
    endedYear: 2026,
    successor: "Renamed from Zoro / aniwatch",
    emoji: "👁️",
    gradient: "from-violet-500 to-fuchsia-500",
    featured: true,
  },
  {
    slug: "kissanime",
    name: "KissAnime",
    status: "shutdown",
    kind: "stream",
    blurb: "Once the most infamous free streamer in the world. Shut down in 2020 amid Japan's piracy crackdown.",
    features: ["Was: Subbed", "Was: Dubbed", "Name abused by clones"],
    endedYear: 2020,
    emoji: "💋",
    gradient: "from-pink-500 to-rose-500",
    featured: true,
  },
  {
    slug: "9anime",
    name: "9anime / Aniwave",
    status: "shutdown",
    kind: "stream",
    blurb: "Hugely popular free streamer that rebranded to Aniwave, then shut itself down in 2024.",
    features: ["Was: Subbed", "Was: Dubbed"],
    endedYear: 2024,
    successor: "Was renamed 9anime → Aniwave",
    emoji: "9️⃣",
    gradient: "from-rose-500 to-orange-400",
  },
  {
    slug: "wakanim",
    name: "Wakanim",
    status: "shutdown",
    kind: "stream",
    blurb: "Sony's European simulcast service (France/Germany/Nordics), shut as its library moved to Crunchyroll.",
    features: ["Was: Subbed", "Was: EU simulcast"],
    founded: 2013,
    endedYear: 2024,
    successor: "Merged into Crunchyroll",
    region: "Europe",
  },
  {
    slug: "animelab",
    name: "AnimeLab",
    status: "shutdown",
    kind: "stream",
    blurb: "The go-to legal streamer for Australia & New Zealand (Madman). Replaced by Crunchyroll in the region.",
    features: ["Was: Subbed", "Was: Dubbed"],
    founded: 2014,
    endedYear: 2022,
    successor: "Migrated to Crunchyroll",
    region: "AU / NZ",
  },
  {
    slug: "vrv",
    name: "VRV",
    status: "shutdown",
    kind: "stream",
    blurb: "Bundle service that once housed Crunchyroll, HIDIVE, and others before being retired.",
    features: ["Was: Bundle", "Was: Channels"],
    founded: 2016,
    endedYear: 2024,
    successor: "Folded into Crunchyroll",
    region: "United States",
  },
  {
    slug: "anime-strike",
    name: "Anime Strike",
    status: "shutdown",
    kind: "stream",
    blurb: "Amazon's short-lived paid anime add-on channel, closed and merged into Prime Video proper.",
    features: ["Was: Subbed", "Was: Channel"],
    founded: 2017,
    endedYear: 2018,
    successor: "Folded into Prime Video",
    region: "United States",
  },
  {
    slug: "daisuki",
    name: "Daisuki",
    status: "shutdown",
    kind: "stream",
    blurb: "Industry-backed legal streamer (Bandai Namco, Toei, Sunrise, et al.) that closed in 2017.",
    features: ["Was: Subbed", "Was: Official"],
    founded: 2013,
    endedYear: 2017,
    region: "Worldwide",
  },
  {
    slug: "viewster",
    name: "Viewster",
    status: "shutdown",
    kind: "stream",
    blurb: "Free, ad-supported streamer with a notable anime catalog before it was wound down.",
    features: ["Was: Free w/ ads", "Was: Subbed"],
    endedYear: 2018,
    region: "Worldwide",
  },
  {
    slug: "neon-alley",
    name: "Neon Alley",
    status: "shutdown",
    kind: "stream",
    blurb: "VIZ Media's dubbed anime channel/service, later rolled into Hulu and discontinued.",
    features: ["Was: Dubbed", "Was: Channel"],
    founded: 2012,
    endedYear: 2014,
    region: "North America",
  },
  {
    slug: "anime-network",
    name: "The Anime Network",
    status: "shutdown",
    kind: "stream",
    blurb: "Sentai's long-running anime channel and streamer, effectively succeeded by HIDIVE.",
    features: ["Was: Subbed", "Was: Dubbed"],
    endedYear: 2017,
    successor: "Succeeded by HIDIVE",
    region: "North America",
  },
  {
    slug: "iflix",
    name: "iflix",
    status: "shutdown",
    kind: "stream",
    blurb: "Southeast Asian streamer with licensed anime; absorbed by Tencent/WeTV after financial trouble.",
    features: ["Was: Subbed"],
    endedYear: 2020,
    successor: "Absorbed into WeTV",
    region: "SE Asia",
  },
  {
    slug: "animixplay",
    name: "AniMixPlay",
    status: "shutdown",
    kind: "stream",
    blurb: "Free aggregator with a slick UI that abruptly shut down in 2022 with a cryptic farewell.",
    features: ["Was: Aggregator", "Was: Subbed"],
    endedYear: 2022,
  },
  {
    slug: "4anime",
    name: "4anime",
    status: "shutdown",
    kind: "stream",
    blurb: "Minimalist free streamer popular for downloads; went offline in 2021 after legal pressure.",
    features: ["Was: Subbed", "Was: Downloads"],
    endedYear: 2021,
  },
  {
    slug: "animekisa",
    name: "AnimeKisa",
    status: "shutdown",
    kind: "stream",
    blurb: "Ad-free free streamer beloved for its clean experience before it went dark.",
    features: ["Was: Ad-free", "Was: Subbed"],
    endedYear: 2021,
  },
  {
    slug: "masterani",
    name: "Masterani.me",
    status: "shutdown",
    kind: "stream",
    blurb: "Highly polished free streamer of the late 2010s, shut down in 2018 under legal pressure.",
    features: ["Was: Subbed", "Was: HD"],
    endedYear: 2018,
  },
  {
    slug: "twist-moe",
    name: "twist.moe",
    status: "shutdown",
    kind: "stream",
    blurb: "Minimalist, invite-flavored free streamer known for high-quality encodes; eventually discontinued.",
    features: ["Was: HD", "Was: Subbed"],
    endedYear: 2023,
  },
  {
    slug: "chia-anime",
    name: "Chia-Anime",
    status: "shutdown",
    kind: "stream",
    blurb: "Old-guard free streaming and download site that faded out late last decade.",
    features: ["Was: Subbed", "Was: Downloads"],
    endedYear: 2019,
  },
  {
    slug: "ryuanime",
    name: "RyuAnime",
    status: "shutdown",
    kind: "stream",
    blurb: "Free streaming aggregator that shut down amid the wave of takedowns.",
    features: ["Was: Subbed"],
    endedYear: 2022,
  },
  {
    slug: "animeultima",
    name: "AnimeUltima",
    status: "shutdown",
    kind: "stream",
    blurb: "Community-driven free streamer that closed at the end of the 2010s.",
    features: ["Was: Subbed", "Was: Community"],
    endedYear: 2019,
  },
  {
    slug: "mangarock",
    name: "MangaRock",
    status: "shutdown",
    kind: "manga",
    blurb: "Wildly popular free manga app that shut down in 2020 and pivoted away under legal pressure.",
    features: ["Was: Free app", "Was: Huge library"],
    endedYear: 2020,
    emoji: "🪨",
    gradient: "from-amber-400 to-orange-500",
  },
  {
    slug: "mangastream",
    name: "MangaStream",
    status: "shutdown",
    kind: "manga",
    blurb: "Influential scanlation site whose 2020 closure reshaped the scanlation landscape.",
    features: ["Was: Scanlations"],
    endedYear: 2020,
  },
  {
    slug: "mangapanda",
    name: "MangaPanda / MangaReader (old)",
    status: "shutdown",
    kind: "manga",
    blurb: "Classic free manga readers from the same operator, shuttered in 2020.",
    features: ["Was: Free", "Was: Large library"],
    endedYear: 2020,
  },
  {
    slug: "kissmanga",
    name: "KissManga",
    status: "shutdown",
    kind: "manga",
    blurb: "The manga sister site of KissAnime; shut down alongside it in 2020.",
    features: ["Was: Free manga", "Name abused by clones"],
    endedYear: 2020,
  },
  {
    slug: "jaiminisbox",
    name: "Jaimini's Box",
    status: "shutdown",
    kind: "manga",
    blurb: "Prominent scanlation group and reader that disbanded in 2021.",
    features: ["Was: Scanlations"],
    endedYear: 2021,
  },
  {
    slug: "mangasee",
    name: "MangaSee / Manga4Life",
    status: "shutdown",
    kind: "manga",
    blurb: "Heavily used free reader (and TachiyomiSY favorite) that went dark, spurring Weeb Central.",
    features: ["Was: Free", "Was: Large library"],
    endedYear: 2024,
    successor: "Users moved to Weeb Central",
  },
  {
    slug: "batoto-original",
    name: "Batoto (original)",
    status: "shutdown",
    kind: "manga",
    blurb: "The original community scanlation host that closed in 2018; later revived by fans as Bato.to.",
    features: ["Was: Scanlations", "Was: Community"],
    founded: 2011,
    endedYear: 2018,
    successor: "Revived as Bato.to",
  },
  {
    slug: "manga-mura",
    name: "Mangamura (漫画村)",
    status: "shutdown",
    kind: "manga",
    blurb: "Japan's most notorious piracy site; its 2018 shutdown and the operator's arrest were a landmark case.",
    features: ["Was: Free manga", "Seized"],
    endedYear: 2018,
    region: "Japan",
  },
  {
    slug: "horriblesubs",
    name: "HorribleSubs",
    status: "shutdown",
    kind: "download",
    blurb: "The de-facto weekly fansub release group for years; disbanded in 2020 and regrouped as SubsPlease.",
    features: ["Was: Torrents", "Was: Weekly subs"],
    endedYear: 2020,
    successor: "Became SubsPlease",
    emoji: "📦",
    gradient: "from-amber-400 to-orange-500",
  },
  {
    slug: "nyaa-se",
    name: "Nyaa Torrents (nyaa.se)",
    status: "shutdown",
    kind: "download",
    blurb: "The original Nyaa, taken offline in 2017; the community rebuilt it as nyaa.si.",
    features: ["Was: Torrents", "Was: Index"],
    endedYear: 2017,
    successor: "Rebuilt as nyaa.si",
  },
  {
    slug: "anitube-br",
    name: "AniTube (Brazil)",
    status: "free",
    kind: "stream",
    blurb: "One of Brazil's biggest free streamers; repeatedly targeted and ISP-blocked by court order.",
    features: ["Subbed (PT)", "Dubbed (PT)"],
    region: "Brazil",
    blockedIn: ["Brazil"],
  },

  // =========================================================================
  // MORE — additional legal, free, and tracker entries
  // =========================================================================
  {
    slug: "adult-swim",
    name: "Adult Swim",
    url: "https://www.adultswim.com",
    status: "legal",
    kind: "stream",
    blurb: "The Toonami home base — streams its dubbed anime block free (with ads) in supported regions.",
    features: ["Free w/ ads", "Dubbed", "Toonami"],
    region: "US / AU / NZ",
  },
  {
    slug: "aniplus-asia",
    name: "Aniplus Asia",
    url: "https://www.aniplus-asia.com",
    status: "legal",
    kind: "stream",
    blurb: "Southeast Asian anime channel and streamer with same-season simulcasts.",
    features: ["Subbed", "Simulcast", "Channel"],
    region: "SE Asia",
  },
  {
    slug: "justwatch",
    name: "JustWatch",
    url: "https://www.justwatch.com",
    status: "legal",
    kind: "database",
    blurb: "Search engine that shows which legal services carry a given anime in your country.",
    features: ["Where to watch", "Legal"],
    region: "Worldwide",
  },
  {
    slug: "anichart",
    name: "AniChart",
    url: "https://anichart.net",
    status: "legal",
    kind: "schedule",
    blurb: "AniList's seasonal chart view for browsing every airing show at a glance.",
    features: ["Seasonal", "Charts"],
    region: "Worldwide",
  },
  {
    slug: "crunchyroll-news",
    name: "Crunchyroll News",
    url: "https://www.crunchyroll.com/news",
    status: "legal",
    kind: "news",
    blurb: "Crunchyroll's editorial arm — announcements, interviews, and features.",
    features: ["News", "Official"],
    region: "Worldwide",
  },
  {
    slug: "animension",
    name: "Animension",
    status: "free",
    kind: "stream",
    blurb: "Free streamer with MAL/AniList integration and an episode-tracking feed.",
    features: ["Subbed", "Tracker sync"],
    region: "Worldwide",
  },
  {
    slug: "animeheaven",
    name: "AnimeHeaven",
    status: "free",
    kind: "stream",
    blurb: "Veteran free streamer that has survived through multiple domains.",
    features: ["Subbed", "Veteran"],
    region: "Worldwide",
  },
  {
    slug: "marin-moe",
    name: "Marin",
    status: "free",
    kind: "stream",
    blurb: "Clean, modern free streaming front-end with tracker sync.",
    features: ["Subbed", "Dubbed", "Modern UI"],
    region: "Worldwide",
  },
  {
    slug: "anime-onsen",
    name: "Anime Onsen",
    status: "free",
    kind: "stream",
    blurb: "Ad-free, invite-flavored free streamer focused on quality playback.",
    features: ["Ad-free", "Subbed", "HD"],
    region: "Worldwide",
  },
  {
    slug: "mangatown",
    name: "MangaTown",
    status: "free",
    kind: "manga",
    blurb: "Long-running free manga reader with a large back catalog.",
    features: ["Free", "Large library"],
    region: "Worldwide",
  },
  {
    slug: "manhuascan",
    name: "ManhuaScan",
    status: "free",
    kind: "manga",
    blurb: "Free reader specializing in Chinese manhua with English translations.",
    features: ["Free", "Manhua"],
    region: "Worldwide",
  },
  {
    slug: "mangaowl",
    name: "MangaOwl",
    status: "free",
    kind: "manga",
    blurb: "Free reader with manga and manhwa and a focus on the latest chapters.",
    features: ["Free", "Manhwa"],
    region: "Worldwide",
  },
  {
    slug: "anirena",
    name: "AniRena",
    status: "free",
    kind: "download",
    blurb: "Public anime torrent index and tracker, an alternative to Nyaa.",
    features: ["Torrents", "Index"],
    region: "Worldwide",
  },

  // =========================================================================
  // DONGHUA — Chinese animation streamers (mostly unofficial)
  // =========================================================================
  {
    slug: "animexin",
    name: "AnimeXin",
    status: "free",
    kind: "donghua",
    blurb: "Go-to free streamer for donghua with multi-language soft-subs.",
    features: ["Donghua", "Multi-sub"],
    region: "Worldwide",
  },
  {
    slug: "animekhor",
    name: "AnimeKhor",
    status: "free",
    kind: "donghua",
    blurb: "Free donghua and anime streamer with frequent updates.",
    features: ["Donghua", "Subbed"],
    region: "Worldwide",
  },
  {
    slug: "donghuastream",
    name: "DonghuaStream",
    status: "free",
    kind: "donghua",
    blurb: "Dedicated free streaming site for Chinese donghua.",
    features: ["Donghua", "Subbed"],
    region: "Worldwide",
  },
  {
    slug: "lmanime",
    name: "LManime",
    status: "free",
    kind: "donghua",
    blurb: "Free streamer focused on donghua with English soft-subs.",
    features: ["Donghua", "Soft-sub"],
    region: "Worldwide",
  },
  {
    slug: "myanime-live",
    name: "MyAnime.live",
    status: "free",
    kind: "donghua",
    blurb: "Free donghua streamer covering ongoing Chinese animation.",
    features: ["Donghua"],
    region: "Worldwide",
  },
  {
    slug: "anime-cube",
    name: "Anime Cube",
    status: "free",
    kind: "donghua",
    blurb: "Free streamer mixing donghua and anime catalogs.",
    features: ["Donghua", "Subbed"],
    region: "Worldwide",
  },

  // =========================================================================
  // LIGHT NOVELS — reading
  // =========================================================================
  {
    slug: "j-novel-club",
    name: "J-Novel Club",
    url: "https://j-novel.club",
    status: "legal",
    kind: "novel",
    blurb: "Licenses and simul-publishes light novels and manga in English.",
    features: ["Official", "Simulpub", "Light novels"],
    region: "Worldwide (most)",
    emoji: "📕",
    gradient: "from-amber-400 to-orange-500",
    featured: true,
  },
  {
    slug: "novelupdates",
    name: "NovelUpdates",
    url: "https://www.novelupdates.com",
    status: "legal",
    kind: "database",
    blurb: "The reference tracker/database for translated light novels and web novels.",
    features: ["Database", "Tracking", "Releases"],
    region: "Worldwide",
  },
  {
    slug: "novelfire",
    name: "NovelFire",
    status: "free",
    kind: "novel",
    blurb: "Large free reader for translated light and web novels.",
    features: ["Free", "Web novels"],
    region: "Worldwide",
  },
  {
    slug: "lightnovelworld",
    name: "LightNovelWorld",
    status: "free",
    kind: "novel",
    blurb: "Popular free reader with a big catalog of translated novels.",
    features: ["Free", "Large library"],
    region: "Worldwide",
  },
  {
    slug: "novelbin",
    name: "Novel Bin",
    status: "free",
    kind: "novel",
    blurb: "Free web-novel reader with a deep back catalog.",
    features: ["Free", "Web novels"],
    region: "Worldwide",
  },
  {
    slug: "freewebnovel",
    name: "FreeWebNovel",
    status: "free",
    kind: "novel",
    blurb: "Free reader aggregating translated and machine-translated novels.",
    features: ["Free", "MTL"],
    region: "Worldwide",
  },
  {
    slug: "ranobes",
    name: "Ranobes",
    status: "free",
    kind: "novel",
    blurb: "Free novel reader popular for fast-updating translations.",
    features: ["Free", "Web novels"],
    region: "Worldwide",
  },
  {
    slug: "wuxiabox",
    name: "Wuxia Box",
    status: "free",
    kind: "novel",
    blurb: "Free reader specializing in Chinese wuxia/xianxia web novels.",
    features: ["Free", "Wuxia / Xianxia"],
    region: "Worldwide",
  },
  {
    slug: "baka-tsuki",
    name: "Baka-Tsuki",
    status: "free",
    kind: "novel",
    blurb: "Veteran fan-translation wiki archiving community light-novel translations.",
    features: ["Fan translations", "Wiki", "Archive"],
    region: "Worldwide",
  },

  // =========================================================================
  // RELEASE SCHEDULE — what airs when
  // =========================================================================
  {
    slug: "animeschedule",
    name: "AnimeSchedule.net",
    url: "https://animeschedule.net",
    status: "legal",
    kind: "schedule",
    blurb: "Clean seasonal timetable with sub/dub air times and tracker sync.",
    features: ["Seasonal", "Sub/Dub times", "Timetable"],
    region: "Worldwide",
    emoji: "🗓️",
    gradient: "from-sky-500 to-indigo-500",
    featured: true,
  },
  {
    slug: "syoboi",
    name: "Syoboi Calendar",
    url: "https://cal.syoboi.jp",
    status: "legal",
    kind: "schedule",
    blurb: "Detailed Japanese broadcast schedule used as a data source by many tools.",
    features: ["JP broadcast", "Calendar"],
    region: "Japan",
  },
  {
    slug: "otaku-calendar",
    name: "Otaku Calendar",
    url: "https://otakucalendar.com",
    status: "legal",
    kind: "schedule",
    blurb: "Calendar of anime, game, and merch release dates.",
    features: ["Calendar", "Releases"],
    region: "Worldwide",
  },
  {
    slug: "lnrelease",
    name: "LNRelease",
    url: "https://lnrelease.github.io",
    status: "legal",
    kind: "schedule",
    blurb: "Tracks upcoming English light-novel print and digital release dates.",
    features: ["Light novels", "Release dates"],
    region: "Worldwide",
  },

  // =========================================================================
  // APPS & TOOLS — open-source readers, players & utilities
  // =========================================================================
  {
    slug: "mihon",
    name: "Mihon",
    url: "https://mihon.app",
    status: "legal",
    kind: "app",
    blurb: "The leading open-source Android manga reader (the successor to Tachiyomi).",
    features: ["Android", "Manga", "Open-source", "Extensions"],
    region: "Worldwide",
    emoji: "📱",
    gradient: "from-emerald-400 to-teal-500",
    featured: true,
  },
  {
    slug: "aniyomi",
    name: "Aniyomi",
    url: "https://aniyomi.org",
    status: "legal",
    kind: "app",
    blurb: "Open-source Android app for both anime and manga, built on the Tachiyomi base.",
    features: ["Android", "Anime", "Manga", "Open-source"],
    region: "Worldwide",
  },
  {
    slug: "kotatsu",
    name: "Kotatsu",
    url: "https://kotatsu.app",
    status: "legal",
    kind: "app",
    blurb: "Free, open-source manga reader for Android with built-in sources.",
    features: ["Android", "Manga", "Open-source"],
    region: "Worldwide",
  },
  {
    slug: "mangayomi",
    name: "Mangayomi",
    url: "https://github.com/kodjodevf/mangayomi",
    status: "legal",
    kind: "app",
    blurb: "Cross-platform open-source app for manga and anime with an extension system.",
    features: ["Universal", "Anime", "Manga", "Open-source"],
    region: "Worldwide",
  },
  {
    slug: "anymex",
    name: "AnymeX",
    url: "https://anymex.vercel.app",
    status: "legal",
    kind: "app",
    blurb: "Cross-platform open-source client for anime, manga, and novels with tracker sync.",
    features: ["Universal", "Tracker sync", "Open-source"],
    region: "Worldwide",
  },
  {
    slug: "cloudstream",
    name: "CloudStream",
    url: "https://github.com/recloudstream/cloudstream",
    status: "legal",
    kind: "app",
    blurb: "Open-source Android streaming app with anime support via extensions.",
    features: ["Android", "Anime", "Open-source", "Extensions"],
    region: "Worldwide",
  },
  {
    slug: "seanime",
    name: "Seanime",
    url: "https://seanime.rahim.app",
    status: "legal",
    kind: "app",
    blurb: "Open-source desktop media server for anime with library and torrent integration.",
    features: ["Desktop", "Anime", "Open-source"],
    region: "Worldwide",
  },
  {
    slug: "suwayomi",
    name: "Suwayomi",
    url: "https://github.com/Suwayomi/Suwayomi-Server",
    status: "legal",
    kind: "app",
    blurb: "Open-source, self-hosted manga server with a web reader (Tachiyomi-compatible).",
    features: ["Desktop", "Self-host", "Manga", "Open-source"],
    region: "Worldwide",
  },
  {
    slug: "lnreader",
    name: "LNReader",
    url: "https://lnreader.org",
    status: "legal",
    kind: "app",
    blurb: "Open-source Android reader for translated light novels.",
    features: ["Android", "Light novels", "Open-source"],
    region: "Worldwide",
  },
  {
    slug: "komga",
    name: "Komga",
    url: "https://komga.org",
    status: "legal",
    kind: "app",
    blurb: "Self-hosted media server for your own manga/comics library.",
    features: ["Self-host", "Library", "Open-source"],
    region: "Worldwide",
  },
  {
    slug: "malsync",
    name: "MAL-Sync",
    url: "https://malsync.moe",
    status: "legal",
    kind: "app",
    blurb: "Browser extension that auto-syncs your progress to MyAnimeList, AniList, Kitsu, and Simkl.",
    features: ["Extension", "Tracker sync", "Open-source"],
    region: "Worldwide",
  },
  {
    slug: "saucenao",
    name: "SauceNAO",
    url: "https://saucenao.com",
    status: "legal",
    kind: "app",
    blurb: "Reverse-image search that finds the source of anime art and screenshots.",
    features: ["Reverse search", "Tool"],
    region: "Worldwide",
  },
  {
    slug: "tracemoe",
    name: "trace.moe",
    url: "https://trace.moe",
    status: "legal",
    kind: "app",
    blurb: "Finds the exact anime, episode, and timestamp from a screenshot.",
    features: ["Reverse search", "Tool"],
    region: "Worldwide",
  },
];

// --- helpers ---------------------------------------------------------------

const PALETTE = [
  "from-violet-500 to-fuchsia-500",
  "from-fuchsia-500 to-pink-500",
  "from-rose-500 to-orange-400",
  "from-amber-400 to-orange-500",
  "from-emerald-400 to-teal-500",
  "from-teal-400 to-cyan-500",
  "from-sky-500 to-indigo-500",
  "from-indigo-500 to-violet-600",
  "from-lime-400 to-emerald-500",
  "from-red-500 to-rose-600",
  "from-cyan-400 to-blue-500",
  "from-purple-500 to-indigo-500",
  "from-yellow-400 to-amber-500",
  "from-pink-500 to-rose-500",
  "from-blue-500 to-violet-500",
];

const KIND_EMOJI: Record<SiteKind, string> = {
  stream: "📺",
  donghua: "🐉",
  manga: "📖",
  novel: "📕",
  download: "🧲",
  database: "🗂️",
  schedule: "🗓️",
  app: "📱",
  news: "📰",
};

function hash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** Deterministic gradient for a site (uses its hand-picked one if set). */
export function gradientFor(site: AnimeSite): string {
  return site.gradient ?? PALETTE[hash(site.slug) % PALETTE.length];
}

/** Emoji for a site — hand-picked, else a per-kind default (🪦 for the defunct). */
export function emojiFor(site: AnimeSite): string {
  if (site.emoji) return site.emoji;
  if (site.status === "shutdown") return "🪦";
  return KIND_EMOJI[site.kind];
}

export function getAllSites(): AnimeSite[] {
  return ANIME_SITES;
}

export function getSite(slug: string): AnimeSite | undefined {
  return ANIME_SITES.find((s) => s.slug === slug);
}

export function isBlocked(site: AnimeSite): boolean {
  return (site.blockedIn?.length ?? 0) > 0;
}

export type RegionGroup = "global" | "asia" | "europe" | "latam" | "other";

/** Bucket a site into a coarse region group (defaults to "global"). */
export function regionGroup(site: AnimeSite): RegionGroup {
  const r = (site.region ?? "").toLowerCase();
  if (
    /japan|china|korea|taiwan|\basia\b|indonesia|hong kong|india|thailand|vietnam|philippines|singapore|malaysia|brunei|cambodia/.test(
      r,
    )
  )
    return "asia";
  if (
    /europe|france|germany|italy|spain|belgium|austria|netherlands|nordic|luxembourg|\beu\b/.test(
      r,
    )
  )
    return "europe";
  if (/latin america|brazil|mexico|latam/.test(r)) return "latam";
  if (/mena|arab|russia|\bcis\b|uae|emirates/.test(r)) return "other";
  return "global";
}

export interface SiteCounts {
  total: number;
  legal: number;
  free: number;
  shutdown: number;
  blocked: number;
}

export function getCounts(sites: AnimeSite[] = ANIME_SITES): SiteCounts {
  return {
    total: sites.length,
    legal: sites.filter((s) => s.status === "legal").length,
    free: sites.filter((s) => s.status === "free").length,
    shutdown: sites.filter((s) => s.status === "shutdown").length,
    blocked: sites.filter(isBlocked).length,
  };
}
