// Downloads a favicon for every site that has a URL into /public/anime-icons,
// then regenerates src/lib/anime/icons-manifest.ts. Run with: npm run icons
//
// Safe to re-run; it overwrites existing icons and the manifest. Free/defunct
// sites have no stored URL, so they keep their letter-tile fallback.
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ANIME_SITES } from "../src/lib/anime/sites";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "public", "anime-icons");

function hostOf(url: string): string | null {
  try {
    return new URL(url).hostname;
  } catch {
    return null;
  }
}

await mkdir(outDir, { recursive: true });

const ok: string[] = [];
for (const s of ANIME_SITES) {
  if (!s.url) continue;
  const host = hostOf(s.url);
  if (!host) continue;
  try {
    const res = await fetch(
      `https://www.google.com/s2/favicons?domain=${host}&sz=64`,
    );
    if (!res.ok) {
      console.warn(`skip ${s.slug} (HTTP ${res.status})`);
      continue;
    }
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length < 100) {
      console.warn(`skip ${s.slug} (empty icon)`);
      continue;
    }
    await writeFile(join(outDir, `${s.slug}.png`), buf);
    ok.push(s.slug);
    process.stdout.write(".");
  } catch (e) {
    console.warn(`err  ${s.slug}: ${(e as Error).message}`);
  }
}

const manifest =
  "// AUTO-GENERATED by `npm run icons`. Do not edit by hand.\n" +
  "// Lists the slugs that have a locally-hosted icon in /public/anime-icons.\n" +
  `export const LOCAL_ICONS: ReadonlySet<string> = new Set(${JSON.stringify(
    ok.sort(),
  )});\n`;
await writeFile(
  join(root, "src", "lib", "anime", "icons-manifest.ts"),
  manifest,
);

console.log(`\n\nSaved ${ok.length} icons → public/anime-icons/`);
console.log("Updated src/lib/anime/icons-manifest.ts");
